### ISSUE TITLE
Lock screen only option

### ISSUE THREAD

**Issue by ViktorKahu** [Doubi88/SlideshowWallpaper#10]
Currently, the options are:

1) Home screen
2) Home screen and lock screen

But the one I need is missing:

3) Lock screen only

**Comment by Doubi88** [comment]
Hi @ViktorKahu,
thanks for reaching out. I would really like to do that, but this selection is provided by Android and I have no influence on that, sorry.
Perhaps you could try to set it for home- and Lockscreen and then set something different for home screen only, if that works.

**Comment by ViktorKahu** [comment]
Hi Doubi,

No worries mate.

In case you are interested, Bnyro managed to do it on his app "Wall You" - works perfectly.

Another idea for you is to implement the ability to use 2 different photo folders for lock screen and home screen.

Regards and good luck.

**Comment by Doubi88** [comment]
Hey, thanks for the hint, I didn't know that app.
The difference here is, that Wall You sets the wallpaper directly to the image you select. Therefore it needs the permission to set the wallpaper, but you can select home screen or lock screen in the app. Slideshow wallpaper only calls the native wallpaper preview screen, that you also see when selecting the wallpaper from the home screen settings. Therefore it doesn't need that permission, but is dependent on what the OS offers on that page.

Regarding the two different backgrounds: I have an idea, how that might work, but it requires a larger change on the overall structure of the app. I'll make an issue for that and see, when I have the time to do that.

**Comment by Doubi88** [comment]
For my ideas on that, see #11
