### ISSUE TITLE
Time intervals suggestion

### ISSUE THREAD

**Issue by VasilisKos** [Doubi88/SlideshowWallpaper#14]
I think the selectable time intervals are too many, and some of them don't make sense. This is not a photo slideshow app, but a live wallpaper. Intervals of seconds don't make sense when using the phone, unless someone has the screen activated just to watch the wallpapers changing, which is not the case under normal everyday use a the phone. On the contrary, some esential longer intervals, like hours and a day, are missing. So, I'd suggest the following ones:
1. 10 secs
2. 30 secs
3. 1 min
4. 5 mins
5. 15 mins
6. 30 mins
7. 1 hour
8. 6 hours
9. 12 hours
10. 24 hours (1 day)

**Comment by Doubi88** [comment]
Great suggestion, thank you. Will do 😊

**Comment by Doubi88** [comment]
Important: Convert removed entries to the nearest one, if selected

**Comment by VasilisKos** [comment]
> 

Sorry, but I don't understand what exactly you mean.

**Comment by Doubi88** [comment]
Sorry, that was just a note for me

**Comment by cloudrac3r** [comment]
Just found out about your app, it's simple and I like it! I like these time intervals too, I came here to comment the same thing. If I get annoyed by the current short timers then I'll test and make a PR to change them for you :)

**Comment by Doubi88** [comment]
Hey @cloudrac3r, that would be really cool, of you could do that. I already changed the intervals in the branch issue-14-seconds-entries-change. I tested the short entries. If you want, you can test `getNextAvailableSecondsEntry` and write the results in a pull request.

**Comment by Doubi88** [comment]
Tested and fixed in current development branch.
