### ISSUE TITLE
Error reading file

### ISSUE THREAD

**Issue by xezwary** [Doubi88/SlideshowWallpaper#17]
I get an error after adding 2748 images, exit the images menu, then re-enter and the images only show "error reading file".
I get just a plain black background in preview and when used as the wallpaper.

**Comment by Doubi88** [comment]
Hi @xezwary,
sorry that it took me so long to answer. That's a tough one. It might be related to that huge number of images, but I don't know. I never selected more than 400.
Perhaps there is an error in the image list. Can I send you an app version, where you can export the image list, so I can check it for errors? From where did you download the app?
Another thing that comes to my mind are the media permissions. To check these, please open the app info of Slideshow Wallpaper, go to "Storage and cache" and scroll down. If this one is correct, there should be an entry "media" saying "2748 items". If that's not the case, that's where the error is.

**Comment by xezwary** [comment]
I downloaded it from F-Droid, version 1.0.2, in storage & cache it says 512 items.
And sure, I'm okay with exporting the image list if it helps.

**Comment by Doubi88** [comment]
Oh no! I found the cause of that. There is a hard coded limit of maximum 512 grants an app can get. See https://issuetracker.google.com/issues/149315521#comment7
I'll have to think of a solution to this. Maybe the app should copy the images to a folder it can access without grants. I'll make new issues for that.

I'm sorry I have no direct solution for you currently. You can only either remove the images showing the error from the list or wait for me to implement the fix.
