### ISSUE TITLE
deleted images cause problems

### ISSUE THREAD

**Issue by dkess** [Doubi88/SlideshowWallpaper#23]
If an image from the slideshow has been deleted:

* when the slideshow tries to set that image as wallpaper, it ends up being solid black
* if I try to remove that image from the slideshow in the app, the app crashes

**Comment by Doubi88** [comment]
Hey, thanks for the report. That should hopefully be an easy fix. I will look into it, as soon as I have the time.

**Comment by Doubi88** [comment]
Fixed in current development branch

**Comment by dkess** [comment]
Thanks so much!!
