### ISSUE TITLE
Scaling artifacts

### ISSUE THREAD

**Issue by fuzzblob** [Doubi88/SlideshowWallpaper#24]
I just started using the app and already love it! Great job on creating such a useful tool <3

There is an issue I ran into though. The "scaling up to fit" option is creating some stepping/pixelation artifacts. I'm suspecting it has to do with a lack of anti-aliasing but I'm not sure.

Running on a Google Pixel 6 on GrapheneOS, android 13. It has a display resolution of 1080 x 2400 which is smaller than all the examples.
I'll attach some screenshots that might show the effect, especially in the circular shapes:

Original resolution 1536 x 3072:
![Screenshot_20230819-175046](https://github.com/Doubi88/SlideshowWallpaper/assets/13321200/da0c12cd-1d10-400e-b6a6-af93b58c208b)

Original resolution 6252 x 3517:
![Screenshot_20230819-180103](https://github.com/Doubi88/SlideshowWallpaper/assets/13321200/7d1f934d-2118-4416-a523-ea5383dd5162)

**Comment by Doubi88** [comment]
Hi @fuzzblob
Thanks for the heads-up. Yes, I didn't consider anti aliasing. I'll look into it, maybe just a flag I have to set.

**Comment by Doubi88** [comment]
I did something on the current development branch. I hope that fixes it.

**Comment by furiseto** [comment]
> I did something on the current development branch. I hope that fixes it.

Looking forward to new update. I also notice this particular problem and glad to hear you are fixing it. Thanks for the app.

**Comment by Doubi88** [comment]
Did the update fix this issue?

**Comment by fuzzblob** [comment]
From what I can tell it looks a lot better. I will install on my spare phone and test a bit more.
