### ISSUE TITLE
Applying the setting don't support only applying to the lock screen

### ISSUE THREAD

**Issue by justtry123TL** [Doubi88/SlideshowWallpaper#29]
Just a feature suggestion, or maybe my launcher doesn't work well with the app?

I can't seem to apply the slideshow wallpaper in the lock screen, it always seem to apply to only allow for applying to the launcher or setting it for both. I just don't want a slideshow wallpaper in my home screen.

**Comment by Doubi88** [comment]
Hi @justtry123TL,
Unfortunately, I have no influence on that. See Issue #10 for an explanation.
