### ISSUE TITLE
Cannot see top task bar font

### ISSUE THREAD

**Issue by justtry123TL** [Doubi88/SlideshowWallpaper#30]
While using white color background images, the text such as time or battery life at the top cannot be seen, as it hadn't adapted to a darker font color, such as grey or black for better visibility.

**Comment by Doubi88** [comment]
Hey @justtry123TL,
Thanks for the hint. I found out there is actually an API for this. It also sounds very easy, so maybe I can add that to the next release.

https://developer.android.com/reference/android/service/wallpaper/WallpaperService.Engine#onComputeColors()

**Comment by oleastre** [comment]
I did not see this issue, but already had a look on the problem as part of the PR I just posted: #31

**Comment by Doubi88** [comment]
Should be fixed in next release.
