### ISSUE TITLE
Redesign image list

### ISSUE THREAD

**Issue by jln-brtn** [Doubi88/SlideshowWallpaper#4]
Hi @Doubi88,
Thanks for your work and your free app. I'm happy to see a game changer on the playstore instead of the full ad apps.

If you agree, I would like to suggest a redesign of the image_list and image_list_entry. I can start by creating a mockup of this new interface and, after your validation, developing it.

Julien

**Comment by Doubi88** [comment]
Hi @jln-brtn,
Thank you for the kind words.
That sounds great, I would love to see your design.
