### ISSUE TITLE
Missing access to all folders 

### ISSUE THREAD

**Issue by PolGZ** [Doubi88/SlideshowWallpaper#46]
On Android 14 (CalyxOS runing on Pixel 5) it doesn't prompt for files permissions and it doesn't show all folders. I can only select from Downloads, Camera or Screenshot albums.

I'd like to pick pictures from other folders.

Great idea, BTW. I've just watched it on fdroid and immediately installed it.

**Comment by Doubi88** [comment]
In the next version, it should show all folders again. I reverted back to the old API and will take a look at that later.
